name: AutoDeployBackend
on: 
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy pipeline
        uses: fifsky/ssh-action@master
        with:
          command: |
            ./Deploy.sh
          host: punchy.servebeer.com
          user: kocetomad
          key: ${{ secrets.PRIVATE_KEY}}
